### ISSUE TITLE
Consider using UNIX-Timestamp instead of HTTP Date for `RateLimit-Reset`

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/draft-polli-ratelimit-headers#15]
## Question

Currently we have

```
ratelimit-reset-value = Retry-After
Retry-After =  HTTP-Date | delta-seconds
```

Instead we could

```
ratelimit-reset-value = UNIX Timestamp | delta-seconds
```

### pro

- simpler to generate and to parseintroduces parsing confu
- compatible with many current implementations (twitter/github)

### cons

- misaligned with `retry-after`;
- could incentive using an absolute time instead of delta-seconds;
- may confuse parsers, as both formats have the same syntax; An arbitrary solution could be
  to state that the max value for delta-seconds is 86400 or a reasonable high value.
- y2k38 problem for UNIX-time as a `32 bit signed integer`  

## Notes

-  We could state something on too-high values in `ratelimit-reset` in the security considerations, though HTTP specs does not seem to contain any of that.
- We could even enforce ONLY `delta-seconds`

**Comment by whiskeysierra** [comment]
> * compatible with many current implementations

That's a good selling point, but to me:

> * may confuse parsers, as both formats have the same syntax; An arbitrary solution could be
>   to state that the max value for delta-seconds is 86400 or a reasonable high value.

this is also a big cons. I had to do this here:

https://github.com/zalando/riptide/blob/197260ef345cad46dc1303c0e0515474c7eb5e7d/riptide-failsafe/src/main/java/org/zalando/riptide/failsafe/EpochSecondsDelayParser.java#L22-L23

I ended up using the maximum distance between timezones which is 26 hours. Pretty tricky already.

**Comment by unleashed** [comment]
Dates have an additional problem, which is that the clocks used for those are usually not monotonically increasing, so they can jump to the future or to the past, and in the cases where they are, clock time can be slowed down to adapt to changes in date, ie. via adjtime(2).

I am in favor of dropping the HTTP-Date alternative and just accepting delta-seconds, and if anything include a UNIX timestamp (for ease of parsing) in the same header:

> RateLimit-Reset: 55;t=1569942780

or

> RateLimit-Reset: 55 (1569942780)

**Comment by ioggstream** [comment]
> clocks are not monotonically increasing as they may be adjusted via adjtime(2)

Good point for avoiding both timestamps and millisecond precision Reset. I'll prepare
a dedicated PR on that. 

> dropping the HTTP-Date alternative and just accepting delta-seconds

reasonable, I like it.

> RateLimit-Reset: 55 (1569942780)

This does not match a structured header.

> RateLimit-Reset: 55;t=1569942780

seems interesting, though this adds a parameter to `RateLimit-Reset`.

Considering that adding a timestamp essentially means having ntp on the server, can we compute the reset moment using `Date` and `RateLimit-Reset`?

**Comment by unleashed** [comment]
> Considering that adding a timestamp essentially means having ntp on the server, can we compute the reset moment using Date and RateLimit-Reset?

Yes, but there is the possibility of the `Date` header being generated by a different server (hence different clock) than the one applying the rate limiting policy.

So for a timestamp included in the new headers by the rate limiting server itself, having both the client and that server's clock synchronized would work. But for the `Date` header to be usable, the server generating it (ie. reverse proxies) should also use a synchronized clock.

I can't see added value to specifying such information unless both ends maintain a synchronized clock, so if such information is finally included perhaps it would be good to explicitly mention the use case of having the involved clocks synchronized between them (directly or via some global clock).
