### ISSUE TITLE
Structured Headers

### ISSUE THREAD

**Issue by mnot** [ioggstream/draft-polli-ratelimit-headers#35]
It would be great if these could be defined as structured headers.

**Comment by ioggstream** [comment]
I tried at first to model that with `sh-` but I was not sure of the outcome.

I'll share some thoughts so that we may get some feedback.

The core functionality of the headers should be to simplify ratelimit processing. This means
that the following syntax MUST be supported:

```
ratelimit-limit: 10      # -> int
ratelimit-remaining: 8   # -> int
ratelimit-reset: 8       # -> int
```

iiuc a suitable `sh-` notation could be

```
limit: sh-integer *( OWS "," OWS limit-member )
remaining: sh-integer
reset: sh-integer
limit-member: sh-integer OWS ";" "w" "=" sh-integer
```

valid values should map to the following data structures. Is that possible?

```
limit: 10                       -> int
limit: 10, 100;w=5              -> [ 10, [10, {"w": 5}] ]
limit: 10, 100;w=5, 1000; w=200 -> [ 10, [100, {"w": 5}], [1000, {"w": 200}]
```

invalid values are:

```
limit: 10, 20, 30                   # it's not clear which
                                    # window applies after the 1st limit
limit: 10, 20; w=10, 30; w=10       # duplicate window values
```

**Comment by unleashed** [comment]
Hey, I just have skimmed over the structured headers draft and I think at a quick glance that adapting the headers is probably feasible. The case of windows is likely to be solvable by using item parameters attached to the limits, as defined in the spec (though they can not be complex values) or by directly using dictionaries. IIUIC we can set restrictions to valid values, so we can, for example, rule out a list of non parameterized integers.

While (I think) that is doable, I wonder whether it is the right thing to do now that we have a few initial implementations done or in the works...?

**Comment by ioggstream** [comment]
@unleashed I'd wait for the final release of structured headers, which is ongoing.
Let's focus on the core spec for now :)

**Comment by ioggstream** [comment]
an `sf-list` seem to work... the problem is how to specify with a more formal notation that:
-  all members MUST be sf-integer
- the first member MUST NOT have  parameters, 
- other members  MUST have the w parameter
- the w parameter MUST BE a sf-integer

```
from http_sfv import List

for h in ('10', '10; w=60', '10; w=60; comment="ciao", 50; w=600; comment="ciao"'):
  l=List();
  l.parse(h.encode())
  print(l.to_json())

---
[[10, {}]]
[[10, {'w': 60}]]
[[10, {'w': 60, 'comment': 'ciao'}], [50, {'w': 600, 'comment': 'ciao'}]]
```

**Comment by ioggstream** [comment]
->

**Comment by reschke** [comment]
There is no formal syntax to do that - just put the constraints into prose.
