### ISSUE TITLE
Add headers considerations

### ISSUE THREAD

**Issue by ioggstream** [ioggstream/draft-polli-ratelimit-headers#74]
## I expect

to add considerations expressed in http semantics https://tools.ietf.org/html/draft-ietf-httpbis-semantics-06#section-4.4 et seq.

- [ ] relationship with caches #76 .
- [x] the ratelimit headers must not be repeated
- [x] `ratelimit-limit` field-value can be a list, but cannot be combined in different headers
- [x] they are response header fields 
- [ ] relations with intermediaries #76 
- [x] values shouldn't be preserved b/w redirects (Not applicable, as they're response headers).
- [x] security considerations
- [ ] allowed in trailers? 
- [x] the field semantics are further refined by the context, such as by existing request methods or status codes: no, they are not.

**Comment by ioggstream** [comment]
An intermediary MUST forward the ratelimit headers.

An intermediary MAY lower the RateLimit-Remaining and RateLimit-Limit values
or raise the RateLimit-Reset only if:
- it is aware of the quota-unit semantic used by the Origin Server;
- implements a quota-policy more restrictive than the one provided
  in the actual headers.

An intermediary MUST NOT alter the RateLimit headers values
in such a way as to communicate a more permissive quota-policy.

An intermediary that does not implement this specification
SHOULD forward request to the Origin Server even if it knows,
by processing the headers, that the request might not be serviced.
The server returning RateLimit headers is the sole responsible of
enforcing the communicated quota policy.

As is the ordinary case for HTTP caching ({{?RFC7234}}), a response with a
RateLimit header fields might be cached and re-used for subsequent requests,
but the RateLimit headers MUST NOT be cached because their values are ephemeral.

**Comment by dret** [comment]
On 2020-01-28 14:19, Roberto Polli wrote:
> An intermediary that does not implement this specification
> SHOULD forward request to the Origin Server even if it knows,
> by processing the headers, that the request might not be serviced.

it seems odd to spec behavior for implementations not following or more 
likely even knowing the spec. whatever HTTP says happens is what should 
happen, i think that's as good as it gets.
